vaadin.launch-browser=true
spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/aijobboard
spring.datasource.username=postgres
spring.datasource.password=@SunIb2024
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true